### ISSUE TITLE
KeyError: 'timeout'

### ISSUE THREAD

**Issue by ibrokemypie** [remyrd/jimpass#14]
When running with the minimal bitwarden config file as ``jp -c ~/.config/jimpass/config.yaml`` results in the following crash:
```
/home/pie/.local/lib/python3.8/site-packages/jimpass/cli.py:55: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config = yaml.load(config)
Traceback (most recent call last):
  File "/home/pie/.local/bin/jp", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/pie/.local/lib/python3.8/site-packages/jimpass/cli.py", line 79, in cli
    Controller(config, MANAGERS).show_items()
  File "/home/pie/.local/lib/python3.8/site-packages/jimpass/controller.py", line 49, in __init__
    self.managers[name] = managers[name](self.config)
  File "/home/pie/.local/lib/python3.8/site-packages/jimpass/managers/bitwarden.py", line 25, in __init__
    self.session_mgr = BitwardenSession(self.config["timeout"], self.config["auto_lock"])
KeyError: 'timeout'
```

Installed with pip locally on arch linux with python 3

**Comment by remyrd** [comment]
Can you post your `config.yaml`? 
Looks like I missed renaming the `timeout` key to `lock_timer` in the code...

**Comment by ibrokemypie** [comment]
Heres the config.yaml used 
```
managers:
  - bitwarden
bitwarden:
  template_str: 'bw: {name}: user {username}'
```

**Comment by remyrd** [comment]
Ok, I released the fix. It should work after you update the pip package. `pip install -U jimpass`
